server:
  port: 8080

spring:
  ai:
    mcp:
      server:
        enabled: false

      client:
        enabled: true
        type: SYNC

        streamable-http:
          connections:
            lesson15-server:
              url: http://localhost:8081
              endpoint: /mcp
